### ISSUE TITLE
When I run  pip install -r requirements.txt 

### ISSUE THREAD

**Issue by jiegege10** [adrijano/Bitcoin-wallet-cracker#19]
When I run  pip install -r requirements.txt 

<img width="783" alt="WX20210923-113637@2x1" src="https://user-images.githubusercontent.com/25316728/134451291-ab607453-7e3e-45d7-b16c-f4529f6e0400.png">

<img width="1784" alt="WX20210923-113610@2x" src="https://user-images.githubusercontent.com/25316728/134451257-6e4c8af4-7b2b-471d-a93f-ed454ca2139c.png">

**Comment by adrijano** [comment]
Wich python you use?

**Comment by jiegege10** [comment]
3.8.5

**Comment by m7jalta** [comment]
pip3 install -r requirements.txt

**Comment by ProKevinPlayz** [comment]
> i get the same error any solution?

did u find solution?

**Comment by adrijano** [comment]
i update requirement.txt try now
