### ISSUE TITLE
What's the success rate on this wallet cracker? have people actually found any working bitcoin wallets?

### ISSUE THREAD

**Issue by ghost** [adrijano/Bitcoin-wallet-cracker#20]
Has anyone running this script actually been able to find a working wallet with a balance? how long did they leave the cracker running for? or does it not matter as it's a random chance if you find one?

just trying to find some reassurance that it's worth running this 24/7 lol.

**Comment by jehamanantonius** [comment]
#11

**Comment by BitcoinBillionairee** [comment]
The guy literally just sent the public wallet address belonging to an exchange and I struggled to get any further info out of him like private keys or recovery phrase. so jehamanantonius, it was worthless. Look it up on a blockchain explorer haha
