### ISSUE TITLE
Adding a wallets checked per second part to the cracker?

### ISSUE THREAD

**Issue by ghost** [adrijano/Bitcoin-wallet-cracker#21]
I think it would be extremely helpful to have a 'wallets per second checked' feature on the top of the cracker, right above the timer at the top.

the dark web ones apparently have it but they're very unreliable and not supported/updated at all from what I've heard.

I think it would be a good way to test the speed of the computers running the cracker and see which ones are the most powerful for running the code. By the way is it the GPU that is being used the most or the RAM?

**Comment by adrijano** [comment]
ok
