### ISSUE TITLE
problem .. Not working

### ISSUE THREAD

**Issue by sokary2004** [adrijano/Bitcoin-wallet-cracker#29]
![1](https://user-images.githubusercontent.com/55245611/154188821-ec4657cc-e68d-4693-96d8-2515cca086f4.jpg)
![2](https://user-images.githubusercontent.com/55245611/154188830-260cf76c-3bd2-4f0c-a133-550269e8acb5.jpg)

1: I tested this program. I noticed that the program output is wrong.
2: I noticed the program selects duplicates of words in a seed, but the old bitcoin wallet program rarely chose duplicates.

**Comment by adrijano** [comment]
ok will fix this

**Comment by adrijano** [comment]
fixed now use for this bc_brainwallet.py

**Comment by adrijano** [comment]
fixed both now you can use both
