### ISSUE TITLE
Where do wallet with balance adresses are ? You mention a txt file but it is not in what i downloaded. Do your code create a file when the program finds a wallet ?

### ISSUE THREAD

**Issue by clemdu92** [adrijano/Bitcoin-wallet-cracker#34]

**Comment by adrijano** [comment]
yes it create file

V pon., 2. maj 2022 12:35 je oseba clemdu92 ***@***.***>
napisala:

**Comment by clemdu92** [comment]
On a previous issue you said it was in the database file is it still that ?

**Comment by adrijano** [comment]
database file got bizcoin addresses with balance when address with balance
is found it will create txt file and address and pvt key

V pon., 2. maj 2022 12:50 je oseba clemdu92 ***@***.***>
napisala:

**Comment by clemdu92** [comment]
Ok thank you

**Comment by clemdu92** [comment]
And how long do i need to let the program run to get a Wallet ?

**Comment by clemdu92** [comment]
~

**Comment by clemdu92** [comment]
And what is the difference for the number of mnemonics word ? Like is it better to search with 24 or 3 ?

**Comment by AlberBhoi** [comment]
Building on Clemdu92 question is BIP0039.txt better or dictionary,txt

**Comment by SimplePotato** [comment]
> And what is the difference for the number of mnemonics word ? Like is it better to search with 24 or 3 ?

You must read a little... [Education](https://vault12.com/securemycrypto/crypto-security-basics/bip39/)

**Comment by SimplePotato** [comment]
> And how long do i need to let the program run to get a Wallet ?

If you guess the wallet with a balance, you could call yourself the luckiest intelligent being in the universe. Now let that sync a little ;)

**Comment by franscorreia1** [comment]
How can I import it

**Comment by StellarStoic** [comment]
add the addresses in the database file

**Comment by franscorreia1** [comment]
No
