### ISSUE TITLE
database

### ISSUE THREAD

**Issue by poudenes** [adrijano/Bitcoin-wallet-cracker#38]
why is there a database with addresses?
When you random select words and check if they exist then you don't need a database list with addresses right?

**Comment by poudenes** [comment]
Ok, installed everything on a RPi4. Did last step 
```python bc.py```
next day the prompt was back, no .txt file, nothing...

**Comment by SimplePotato** [comment]
> Ok, installed everything on a RPi4. Did last step `python bc.py` next day the prompt was back, no .txt file, nothing...

I salute your enthusiasm 🖖

**Comment by poudenes** [comment]
yes but without success haha
