### ISSUE TITLE
No. of words input is always +1 in output 

### ISSUE THREAD

**Issue by StellarStoic** [adrijano/Bitcoin-wallet-cracker#39]
![Screenshot (70)](https://user-images.githubusercontent.com/34000272/179425469-468ee483-7713-48e2-b02e-18b5ff57bfd2.png)

**Comment by SimplePotato** [comment]
- I also noticed that when running bc.py the words output is always +1.  (So if you want to get 12 words, you gotta set "Number of mnemonic words" to 11)

- But when you run bc_brainwallet.py the word count output is the same as the input is.

**Comment by adrijano** [comment]
+ 1 is password
