### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by ujhzxbqinjhv1** [adrijano/Bitcoin-wallet-cracker#42]
when checking the mnemonics do not fit wallets, if you press stop and check at least one, it will turn out to be incorrect

**Comment by adrijano** [comment]
For that you got other file, but remember this is just for aducational purpeses

**Comment by ujhzxbqinjhv1** [comment]
conducted a test, left only one wallet in the file and 12 identical words from this wallet, while the program did not find this wallet ...
