### ISSUE TITLE
Having issue and errors 

### ISSUE THREAD

**Issue by fitch20** [adrijano/Bitcoin-wallet-cracker#46]
@adrijano 
Please I need your help on fixing mine , it’s giving me a huge head ache. 
I don’t mind paying for your service and help.
Kindly hit me up on telegram @fitch24

**Comment by adrijano** [comment]
Hi

**Comment by adrijano** [comment]
I added you on telegram

**Comment by fitch20** [comment]
I saw your texts, but you made it unable for me to reply you. It’s as if you set up a group which only you can send stuffs there. 
![Uploading 520C554D-9BD1-4599-AF25-5C9119FD924A.png…]()
